function validate_bootstrap_csv(B)
%VALIDATE_BOOTSTRAP_CSV  Bootstrap SE validation on the shared CSV datasets
%(../data/dataset_A.csv etc., generated by generate_synthetic_data.py).
%
% For each dataset, prints Theoretical SE, OLS SE, and Bootstrap SE
% (via bootstrp) for beta1 and beta2, so results can be compared directly
% against the Python version (validate_bootstrap_csv.py) running on the
% same CSV files.
%
% Usage:
%   validate_bootstrap_csv()      % B=1000
%   validate_bootstrap_csv(200)

if nargin < 1, B = 1000; end

rng(0);

data_dir = fullfile(fileparts(mfilename('fullpath')), '..', 'data');
info     = readtable(fullfile(data_dir, 'dataset_info.csv'), 'TextType', 'string');

names = ["A", "B", "C"];
w = 80;

fprintf('\nB = %d bootstrap resamples per dataset\n\n', B);

% ── Compute everything once per dataset ─────────────────────────────────
res = struct();
for i = 1:numel(names)
    name = names(i);
    T  = readtable(fullfile(data_dir, sprintf('dataset_%s.csv', name)));
    x1 = T.x1; x2 = T.x2; y = T.y;

    row   = info(info.dataset == name, :);
    sigma = row.sigma;

    est   = fit_ols(x1, x2, y);
    se_an = analytical_se(x1, x2, sigma);
    se_ol = ols_se(x1, x2, y);
    boot  = bootstrp(B, @bootfun, x1, x2, y);

    res.(name).true_b1 = row.true_beta1;
    res.(name).true_b2 = row.true_beta2;
    res.(name).est     = est;
    res.(name).se_an   = se_an;
    res.(name).se_ol   = se_ol;
    res.(name).boot    = boot;
end

% ── SE summary tables (Validation 1) ────────────────────────────────────
for col = 1:2
    if col == 1
        label = 'beta1';
    else
        label = 'beta2';
    end

    fprintf('  %s summary\n', label);
    fprintf('  %s\n', repmat('-', 1, w));
    fprintf('  %-12s %9s %9s %15s %8s %14s\n', '', 'True', 'Est.', 'Theoretical SE', 'OLS SE', 'Bootstrap SE');
    fprintf('  %s\n', repmat('-', 1, w));

    for i = 1:numel(names)
        name = names(i);
        r = res.(name);
        if col == 1
            true_v = r.true_b1;
        else
            true_v = r.true_b2;
        end
        se_bo = std(r.boot(:,col), 0, 1);
        fprintf('  Dataset %-4s %9.4f %9.4f %15.4f %8.4f %14.4f\n', ...
            name, true_v, r.est(col), r.se_an(col), r.se_ol(col), se_bo);
    end
    fprintf('  %s\n\n', repmat('-', 1, w));
end

% ── Pairwise tests on beta1 (Validation 3) ──────────────────────────────
fprintf('  Pairwise tests on beta1\n');
fprintf('  %s\n', repmat('-', 1, w));
fprintf('  %-10s %-8s %20s %10s %16s\n', 'Comparison', 'Test', 'Statistic', 'p-value', 'Decision (a=0.05)');
fprintf('  %s\n', repmat('-', 1, w));

pairs = {'A vs B', 'A', 'B'; 'A vs C', 'A', 'C'};
for i = 1:size(pairs, 1)
    label = pairs{i,1};
    rX = res.(pairs{i,2});
    rY = res.(pairs{i,3});

    bX1 = rX.boot(:,1); bY1 = rY.boot(:,1);
    diff_  = rX.est(1) - rY.est(1);
    se_d   = sqrt(var(bX1) + var(bY1));
    z      = diff_ / se_d;
    p_z    = 2 * (1 - normcdf(abs(z)));
    D      = bX1 - bY1;
    pc     = prctile(D, [2.5, 97.5]);
    sig_ci = pc(1) > 0 || pc(2) < 0;

    if p_z < 0.05, rej_z = 'Reject H0'; else, rej_z = 'Fail to reject'; end
    if sig_ci,     rej_ci = 'Reject H0'; else, rej_ci = 'Fail to reject'; end

    stat_str = sprintf('z = %.4f', z);
    ci_str   = sprintf('[%.4f, %.4f]', pc(1), pc(2));
    true_diff = rX.true_b1 - rY.true_b1;

    fprintf('  %-10s %-8s %20s %10.4f %16s\n', label, 'Z-test', stat_str, p_z, rej_z);
    fprintf('  %-10s %-8s %20s %10s %16s\n', '', '95% CI', ci_str, '-', rej_ci);
    fprintf('  %-10s (true delta beta1=%+.4f,  observed diff=%+.4f)\n', '', true_diff, diff_);
    fprintf('  %s\n', repmat('.', 1, w));
end
fprintf('  %s\n', repmat('-', 1, w));

end


% ── Core functions (same as validate_bootstrap.m) ───────────────────────

function beta = fit_ols(x1, x2, y)
X    = [ones(numel(x1), 1), x1, x2];
b    = X \ y;
beta = b(2:3);
end


function beta = bootfun(x1, x2, y)
X    = [ones(numel(x1), 1), x1, x2];
b    = X \ y;
beta = b(2:3)';
end


function se = analytical_se(x1, x2, sigma)
X       = [ones(numel(x1), 1), x1, x2];
XtX_inv = inv(X' * X);
se      = sigma * sqrt([XtX_inv(2,2); XtX_inv(3,3)]);
end


function se = ols_se(x1, x2, y)
X       = [ones(numel(x1), 1), x1, x2];
b       = X \ y;
rss     = sum((y - X * b).^2);
[n, p]  = size(X);
sigma2  = rss / (n - p);
XtX_inv = inv(X' * X);
se      = sqrt(sigma2 * [XtX_inv(2,2); XtX_inv(3,3)]);
end
