function validate_bootstrap(B, S)
%VALIDATE_BOOTSTRAP  Bootstrap validation using MATLAB's Statistics and
%Machine Learning Toolbox (bootstrp / bootci).
%
% Validations 1 and 3b run on the SHARED CSV datasets in ../data/
% (dataset_A.csv, dataset_B.csv, dataset_C.csv, dataset_info.csv,
% generated by ../generate_synthetic_data.py), so results are directly
% comparable against validate_bootstrap_csv.m / validate_bootstrap_csv.py.
%
% Validations 2 and 3a are Monte Carlo checks that require repeatedly
% generating S fresh random datasets; these continue to generate their
% own data, using Dataset A's true parameters (beta0, beta1, beta2, sigma,
% n) from dataset_info.csv as the data-generating process.
%
% Three checks:
%   1. SE accuracy  - bootstrp SE vs analytical SE / OLS SE (Dataset A, CSV)
%   2. CI coverage  - bootci percentile CI covers the true beta ~95% of time
%   3. Two-sample tests
%        (a) H0: b1_A = b1_B  -> FPR ~ 0.05  (fresh random pairs)
%        (b) Summary table + pairwise A-vs-B / A-vs-C tests (CSV datasets)
%
% Usage:
%   validate_bootstrap()         % B=1000, S=500
%   validate_bootstrap(200, 100) % quick

if nargin < 1, B = 1000; end
if nargin < 2, S = 500;  end

rng(0);

data_dir = fullfile(fileparts(mfilename('fullpath')), '..', 'data');
info     = readtable(fullfile(data_dir, 'dataset_info.csv'), 'TextType', 'string');

rowA   = info(info.dataset == "A", :);
beta0  = rowA.true_beta0;
beta1A = rowA.true_beta1;
beta2  = rowA.true_beta2;
sigmaA = rowA.sigma;
n      = rowA.n;

fprintf('\nModel:  y = b0 + b1*x1 + b2*x2 + eps,   eps ~ N(0, sigma^2)\n');
fprintf('Validations 1 & 3b use shared CSV datasets in %s\n', data_dir);
fprintf('Validations 2 & 3a generate fresh data from Dataset A''s DGP:\n');
fprintf('  b0=%.4f, b1=%.4f, b2=%.4f, sigma=%.4f, n=%d\n', beta0, beta1A, beta2, sigmaA, n);
fprintf('Setup:  B=%d,  S=%d\n', B, S);

val1_se(B, data_dir, info);
val2_coverage(n, B, S, beta0, beta1A, beta2, sigmaA);
val3_two_sample(B, S, data_dir, info, n, beta0, beta1A, beta2, sigmaA);

fprintf('\nDone.\n');

end


% ── Core functions ──────────────────────────────────────────────────────

function [x1, x2, y] = generate_data(beta0, beta1, beta2, sigma, n)
x1  = randn(n, 1);
x2  = randn(n, 1);
eps = sigma * randn(n, 1);
y   = beta0 + beta1 * x1 + beta2 * x2 + eps;
end


function beta = fit_ols(x1, x2, y)
% OLS estimates [b1; b2]
X    = [ones(numel(x1), 1), x1, x2];
b    = X \ y;
beta = b(2:3);
end


function beta = bootfun(x1, x2, y)
% Row-vector version for bootstrp/bootci: [b1, b2]
X    = [ones(numel(x1), 1), x1, x2];
b    = X \ y;
beta = b(2:3)';
end


function se = analytical_se(x1, x2, sigma)
% Theoretical SE = sigma * sqrt(diag[(X'X)^-1])  (true sigma, simulation only)
X       = [ones(numel(x1), 1), x1, x2];
XtX_inv = inv(X' * X);
se      = sigma * sqrt([XtX_inv(2,2); XtX_inv(3,3)]);
end


function se = ols_se(x1, x2, y)
% OLS SE = sigma_hat * sqrt(diag[(X'X)^-1]),  sigma_hat^2 = RSS/(n-p)
X       = [ones(numel(x1), 1), x1, x2];
b       = X \ y;
rss     = sum((y - X * b).^2);
[n, p]  = size(X);
sigma2  = rss / (n - p);
XtX_inv = inv(X' * X);
se      = sqrt(sigma2 * [XtX_inv(2,2); XtX_inv(3,3)]);
end


% ── Validation 1: SE accuracy (Dataset A, from CSV) ─────────────────────

function val1_se(B, data_dir, info)
fprintf('\n%s\n', repmat('=', 1, 60));
fprintf('  Validation 1: Three SE estimates - Theoretical, OLS, Bootstrap\n');
fprintf('  (Dataset A, shared CSV)\n');
fprintf('%s\n', repmat('=', 1, 60));

T  = readtable(fullfile(data_dir, 'dataset_A.csv'));
x1 = T.x1; x2 = T.x2; y = T.y;

row   = info(info.dataset == "A", :);
sigma = row.sigma;

se_an = analytical_se(x1, x2, sigma);
se_ol = ols_se(x1, x2, y);

% bootstrp: B-by-2 matrix, columns = [b1*, b2*]
boot_betas = bootstrp(B, @bootfun, x1, x2, y);
se_bo = std(boot_betas, 0, 1)';   % ddof=1 (default normalization in MATLAB std)

w = 56;
fprintf('\n  %s\n', repmat('-', 1, w));
fprintf('  %6s %16s %10s %14s\n', '', 'Theoretical SE', 'OLS SE', 'Bootstrap SE');
fprintf('  %6s %16s %10s %14s\n', '', 'sig*sqrt[(XX)-1]', 'sigh*..', 'std(b*)');
fprintf('  %s\n', repmat('-', 1, w));
fprintf('  %-6s %16.4f %10.4f %14.4f\n', 'b1', se_an(1), se_ol(1), se_bo(1));
fprintf('  %-6s %16.4f %10.4f %14.4f\n', 'b2', se_an(2), se_ol(2), se_bo(2));
fprintf('  %s\n', repmat('-', 1, w));
fprintf('\n  Theoretical SE: uses true sigma (simulation only).\n');
fprintf('  OLS SE:         uses sigma_hat from residuals (practical).\n');
fprintf('  Bootstrap SE:   non-parametric, no distributional assumption.\n');
end


% ── Validation 2: CI coverage (fresh random data, Dataset A's DGP) ──────

function val2_coverage(n, B, S, beta0, beta1, beta2, sigma)
fprintf('\n%s\n', repmat('=', 1, 60));
fprintf('  Validation 2: 95%% Bootstrap CI Coverage (bootci, percentile)\n');
fprintf('  (fresh random data, Dataset A''s DGP)\n');
fprintf('%s\n', repmat('=', 1, 60));
fprintf('  %d independent datasets x %d bootstrap resamples each.\n', S, B);

cov1 = 0; cov2 = 0;
for s = 1:S
    [x1, x2, y] = generate_data(beta0, beta1, beta2, sigma, n);
    ci = bootci(B, {@bootfun, x1, x2, y}, 'type', 'percentile');
    % ci is 2-by-2: rows = [lower; upper], columns = [b1, b2]
    if ci(1,1) <= beta1 && beta1 <= ci(2,1), cov1 = cov1 + 1; end
    if ci(1,2) <= beta2 && beta2 <= ci(2,2), cov2 = cov2 + 1; end
end

fprintf('\n  %6s %10s  %8s  %6s\n', '', 'Coverage', 'Target', 'Pass?');
fprintf('  %s\n', repmat('-', 1, 36));
labels = {'b1', 'b2'};
covs   = [cov1, cov2] / S;
for i = 1:2
    if covs(i) >= 0.90 && covs(i) <= 1.00
        ok = 'PASS';
    else
        ok = 'FAIL';
    end
    fprintf('  %-6s %10.3f  %8s  %6s\n', labels{i}, covs(i), '0.95', ok);
end
end


% ── Validation 3: Two-sample test ───────────────────────────────────────

function val3_two_sample(B, S, data_dir, info, n, beta0, beta1A, beta2, sigmaA)
fprintf('\n%s\n', repmat('=', 1, 60));
fprintf('  Validation 3: Two-Sample Z-Test and CI (bootstrp / bootci)\n');
fprintf('%s\n', repmat('=', 1, 60));

% ── 3a: H0 true - FPR check (fresh random pairs, Dataset A's DGP) ────
fprintf('\n  3a. H0: b1_A = b1_B = %.4f  ->  FPR should be ~ 0.05\n', beta1A);
fprintf('      %d independent pairs, %d bootstrap resamples each (fresh data).\n', S, B);

fp_z = 0; fp_ci = 0;
for s = 1:S
    [x1A, x2A, yA] = generate_data(beta0, beta1A, beta2, sigmaA, n);
    [x1B, x2B, yB] = generate_data(beta0, beta1A, beta2, sigmaA, n);

    bootA = bootstrp(B, @bootfun, x1A, x2A, yA);
    bootB = bootstrp(B, @bootfun, x1B, x2B, yB);
    bA1 = bootA(:,1); bB1 = bootB(:,1);

    eA = fit_ols(x1A, x2A, yA); eA1 = eA(1);
    eB = fit_ols(x1B, x2B, yB); eB1 = eB(1);

    se_d = sqrt(var(bA1) + var(bB1));
    z    = (eA1 - eB1) / se_d;
    p_z  = 2 * (1 - normcdf(abs(z)));

    D  = bA1 - bB1;
    pc = prctile(D, [2.5, 97.5]);

    if p_z < 0.05, fp_z = fp_z + 1; end
    if pc(1) > 0 || pc(2) < 0, fp_ci = fp_ci + 1; end
end

fprintf('\n      FPR z-test : %.3f   (expected ~ 0.05)\n', fp_z / S);
fprintf('      FPR CI     : %.3f   (expected ~ 0.05)\n', fp_ci / S);

% ── 3b: All three datasets - summary + pairwise tests (CSV) ──────────
namesABC = ["A", "B", "C"];
rowB = info(info.dataset == "B", :);
rowC = info(info.dataset == "C", :);
fprintf('\n  3b. Three datasets (shared CSV): A (b1=%.4f), B (b1=%.4f), C (b1=%.4f)\n', ...
    beta1A, rowB.true_beta1, rowC.true_beta1);

res = struct();
for i = 1:numel(namesABC)
    name = namesABC(i);
    T  = readtable(fullfile(data_dir, sprintf('dataset_%s.csv', name)));
    x1 = T.x1; x2 = T.x2; y = T.y;

    row   = info(info.dataset == name, :);
    sigma = row.sigma;

    est   = fit_ols(x1, x2, y);
    se_an = analytical_se(x1, x2, sigma);
    se_ol = ols_se(x1, x2, y);
    boot  = bootstrp(B, @bootfun, x1, x2, y);

    res.(name).true_b1 = row.true_beta1;
    res.(name).true_b2 = row.true_beta2;
    res.(name).est     = est;
    res.(name).se_an   = se_an;
    res.(name).se_ol   = se_ol;
    res.(name).boot    = boot;
end

w = 80;

% Table 1: b1
fprintf('\n  b1 summary\n');
fprintf('  %s\n', repmat('-', 1, w));
fprintf('  %-12s %9s %9s %15s %8s %14s\n', '', 'True b1', 'Est. b1', 'Theoretical SE', 'OLS SE', 'Bootstrap SE');
fprintf('  %s\n', repmat('-', 1, w));
names = {'Dataset A', 'Dataset B', 'Dataset C'};
for i = 1:3
    name = namesABC(i);
    r = res.(name);
    se_bo = std(r.boot(:,1), 0, 1);
    fprintf('  %-12s %9.4f %9.4f %15.4f %8.4f %14.4f\n', ...
        names{i}, r.true_b1, r.est(1), r.se_an(1), r.se_ol(1), se_bo);
end
fprintf('  %s\n', repmat('-', 1, w));

% Table 2: b2
fprintf('\n  b2 summary\n');
fprintf('  %s\n', repmat('-', 1, w));
fprintf('  %-12s %9s %9s %15s %8s %14s\n', '', 'True b2', 'Est. b2', 'Theoretical SE', 'OLS SE', 'Bootstrap SE');
fprintf('  %s\n', repmat('-', 1, w));
for i = 1:3
    name = namesABC(i);
    r = res.(name);
    se_bo = std(r.boot(:,2), 0, 1);
    fprintf('  %-12s %9.4f %9.4f %15.4f %8.4f %14.4f\n', ...
        names{i}, r.true_b2, r.est(2), r.se_an(2), r.se_ol(2), se_bo);
end
fprintf('  %s\n', repmat('-', 1, w));

% Table 3: pairwise tests on b1
fprintf('\n  Pairwise tests on b1\n');
fprintf('  %s\n', repmat('-', 1, w));
fprintf('  %-10s %-8s %20s %10s %16s\n', 'Comparison', 'Test', 'Statistic', 'p-value', 'Decision (a=0.05)');
fprintf('  %s\n', repmat('-', 1, w));

pairs = {'A vs B', 'A', 'B'; 'A vs C', 'A', 'C'};
for i = 1:size(pairs, 1)
    label = pairs{i,1};
    rX = res.(pairs{i,2});
    rY = res.(pairs{i,3});

    bX1 = rX.boot(:,1); bY1 = rY.boot(:,1);
    diff_  = rX.est(1) - rY.est(1);
    se_d   = sqrt(var(bX1) + var(bY1));
    z      = diff_ / se_d;
    p_z    = 2 * (1 - normcdf(abs(z)));
    D      = bX1 - bY1;
    pc     = prctile(D, [2.5, 97.5]);
    sig_ci = pc(1) > 0 || pc(2) < 0;

    if p_z < 0.05, rej_z = 'Reject H0'; else, rej_z = 'Fail to reject'; end
    if sig_ci,     rej_ci = 'Reject H0'; else, rej_ci = 'Fail to reject'; end

    stat_str  = sprintf('z = %.4f', z);
    ci_str    = sprintf('[%.4f, %.4f]', pc(1), pc(2));
    true_diff = rX.true_b1 - rY.true_b1;

    fprintf('  %-10s %-8s %20s %10.4f %16s\n', label, 'Z-test', stat_str, p_z, rej_z);
    fprintf('  %-10s %-8s %20s %10s %16s\n', '', '95% CI', ci_str, '-', rej_ci);
    fprintf('  %-10s (true delta b1=%+.4f,  observed diff=%+.4f)\n', '', true_diff, diff_);
    fprintf('  %s\n', repmat('.', 1, w));
end
fprintf('  %s\n', repmat('-', 1, w));
end
