"""
Bootstrap SE validation on the shared CSV datasets (./data/dataset_A.csv etc.,
generated by generate_synthetic_data.py).

For each dataset, prints Theoretical SE, OLS SE, and Bootstrap SE for
beta1 and beta2, so results can be compared directly against the MATLAB
version (Matlab/validate_bootstrap_csv.m) running on the same CSV files.

Usage:
    python validate_bootstrap_csv.py            # B=1000
    python validate_bootstrap_csv.py --B 200
"""

import argparse
import os
import numpy as np
import pandas as pd
from scipy.stats import norm


def fit_ols(x1, x2, y):
    X    = np.column_stack([np.ones(len(x1)), x1, x2])
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    return float(beta[1]), float(beta[2])


def analytical_se(x1, x2, sigma):
    X       = np.column_stack([np.ones(len(x1)), x1, x2])
    XtX_inv = np.linalg.inv(X.T @ X)
    return (sigma * np.sqrt(XtX_inv[1, 1]),
            sigma * np.sqrt(XtX_inv[2, 2]))


def ols_se(x1, x2, y):
    X       = np.column_stack([np.ones(len(x1)), x1, x2])
    beta    = np.linalg.lstsq(X, y, rcond=None)[0]
    rss     = np.sum((y - X @ beta) ** 2)
    n, p    = X.shape
    sigma_hat_sq = rss / (n - p)
    XtX_inv = np.linalg.inv(X.T @ X)
    return (np.sqrt(sigma_hat_sq * XtX_inv[1, 1]),
            np.sqrt(sigma_hat_sq * XtX_inv[2, 2]))


def bootstrap_betas(x1, x2, y, B, rng):
    n  = len(x1)
    b1 = np.empty(B)
    b2 = np.empty(B)
    for b in range(B):
        idx = rng.choice(n, size=n, replace=True)
        b1[b], b2[b] = fit_ols(x1[idx], x2[idx], y[idx])
    return b1, b2


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--B", type=int, default=1000, help="Bootstrap iterations (default 1000)")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    rng  = np.random.default_rng(args.seed)

    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
    info     = pd.read_csv(os.path.join(data_dir, "dataset_info.csv")).set_index("dataset")

    print(f"\nB = {args.B} bootstrap resamples per dataset\n")

    # ── Compute everything once per dataset ────────────────────────────
    res = {}
    for name in ["A", "B", "C"]:
        df = pd.read_csv(os.path.join(data_dir, f"dataset_{name}.csv"))
        x1, x2, y = df["x1"].values, df["x2"].values, df["y"].values

        row   = info.loc[name]
        sigma = row["sigma"]

        est1, est2   = fit_ols(x1, x2, y)
        an1, an2     = analytical_se(x1, x2, sigma)
        ol1, ol2     = ols_se(x1, x2, y)
        boot1, boot2 = bootstrap_betas(x1, x2, y, args.B, rng)

        res[name] = dict(
            true_b1=row["true_beta1"], true_b2=row["true_beta2"],
            est1=est1, est2=est2,
            an1=an1, an2=an2, ol1=ol1, ol2=ol2,
            boot1=boot1, boot2=boot2,
        )

    # ── SE summary tables (Validation 1) ────────────────────────────────
    w = 80
    for label, header in [("beta1", "beta1 summary"), ("beta2", "beta2 summary")]:
        print(f"  {header}")
        print("  " + "-" * w)
        print(f"  {'':12} {'True':>9} {'Est.':>9} {'Theoretical SE':>15} {'OLS SE':>8} {'Bootstrap SE':>14}")
        print("  " + "-" * w)
        for name in ["A", "B", "C"]:
            r = res[name]
            if label == "beta1":
                true_v, est_v, an_v, ol_v, bo_v = r["true_b1"], r["est1"], r["an1"], r["ol1"], r["boot1"].std(ddof=1)
            else:
                true_v, est_v, an_v, ol_v, bo_v = r["true_b2"], r["est2"], r["an2"], r["ol2"], r["boot2"].std(ddof=1)
            print(f"  Dataset {name:<4} {true_v:>9.4f} {est_v:>9.4f} {an_v:>15.4f} {ol_v:>8.4f} {bo_v:>14.4f}")
        print("  " + "-" * w)
        print()

    # ── Pairwise tests on beta1 (Validation 3) ──────────────────────────
    def pairwise_test(rX, rY):
        diff   = rX["est1"] - rY["est1"]
        se_d   = np.sqrt(rX["boot1"].std(ddof=1)**2 + rY["boot1"].std(ddof=1)**2)
        z      = diff / se_d
        p_z    = 2 * norm.sf(abs(z))
        D      = rX["boot1"] - rY["boot1"]
        lo, hi = np.percentile(D, [2.5, 97.5])
        sig_ci = (lo > 0) or (hi < 0)
        rej_z  = "Reject H0" if p_z < 0.05 else "Fail to reject"
        rej_ci = "Reject H0" if sig_ci     else "Fail to reject"
        return diff, z, p_z, lo, hi, rej_z, rej_ci

    print("  Pairwise tests on beta1")
    print("  " + "-" * w)
    print(f"  {'Comparison':<10} {'Test':<8} {'Statistic':>20} {'p-value':>10} {'Decision (a=0.05)':>16}")
    print("  " + "-" * w)
    for label, nameX, nameY in [("A vs B", "A", "B"), ("A vs C", "A", "C")]:
        rX, rY = res[nameX], res[nameY]
        diff, z, p_z, lo, hi, rej_z, rej_ci = pairwise_test(rX, rY)
        ci_str = f"[{lo:.4f}, {hi:.4f}]"
        true_diff = rX["true_b1"] - rY["true_b1"]
        print(f"  {label:<10} {'Z-test':<8} {'z = ' + f'{z:.4f}':>20} {p_z:>10.4f} {rej_z:>16}")
        print(f"  {'':10} {'95% CI':<8} {ci_str:>20} {'-':>10} {rej_ci:>16}")
        print(f"  {'':10} (true delta beta1={true_diff:+.4f},  observed diff={diff:+.4f})")
        print("  " + "." * w)
    print("  " + "-" * w)


if __name__ == "__main__":
    main()
